# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c114ee1c4cb60571c125d3b77dd3c146bcab8a3d94bdbddf484c10aa20b8e181d24efd8c8baee95889a7d5387295e7ed53b1bc28f34e64fd629054b54e1a311a

test:
  secret_key_base: c1f868fb27c048e3e09160f6285977e9b1b1fee47ff6e098db5005cb6d40931b2e1045c41428ec0f0dd80addd4350b7162b7e1c6a37c453608fc5da3f8d17084

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
